#db.driver=org.postgresql.Driver
#db.url=jdbc:postgresql://127.0.0.1:5432/onaccountx
#db.username=postgres
#db.password=postgres

db.driver=oracle.jdbc.driver.OracleDriver
db.url=jdbc:oracle:thin:@127.0.0.1/orcl
db.username=c##oa
db.password=1qaz@WSX

pool.initialSize=10


