# Revored file level is INFO, output to "stdout"
log4j.rootLogger=INFO, stdout

# "hbm2ddl" level is DEBUG
log4j.category.org.hibernate.tool.hbm2ddl=DEBUG

# "SQL" level is DEBUG
log4j.category.org.hibernate.SQL=DEBUG

# setting "stdout"
log4j.appender.stdout=org.apache.log4j.ConsoleAppender

# setting "stdout" layout & format
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%-d{yyyy-MM-dd HH:mm:ss, SSS} [%c]-[%p] %m%n

